<?php

namespace TaskApp\Widgets;

/**
 *  |--------------------------------------------------------------------------
 *  |   You can use the below snippets to override the defaults.
 *  |====== Remove this doc block if you don't need it ========
 *  |--------------------------------------------------------------------------
 *  | public $contextAs = '$data'; (default : '$data')
 *  | public $controller = '\App\ClassPath\ُSomeClass@someMethod'; (optional)
 *  | public $presenter = \App\ClassPath\WidgetPresenter::class; (optional)
 *  | public $minifyOutput = true; (use it to override the default value in config file)
 *  | public $cacheTags = []; (optional) (Available for all cache driver)
 *  | public $cacheLifeTime = 0;   (use it to override the default value in config file)
 *  | public $cacheView = false; You may only cache the controller result. (default : true)
 *  | public $template; (optional) (By default it looks for the view file generated by artisan)
 *  |--------------------------------------------------------------------------
 */
class StatesSelect
{
    public $cacheLifeTime = 10;
    public $template = 'Task::StatesSelectView';
    public static $states = [
        'done' => 'Done :)',
        'doing' => 'Doing ...',
        'failed' => 'Failed :(',
        'skipped' => 'Skipped :|',
        'not_started' => 'Not Started',

    ];
    public function data()
	{
		return ['states' => self::$states];
	}
}
